---

variables:
  - &ci_image 'cont-reg.bjodah.se:443/bjodah/triceratops-8:8'

when:
  - event: [push]  # pull_request, tag, cron,

steps:

  - name: build-and-test
    image: *ci_image
    privileged: true
    environment:
      COMPILER_LAUNCHER: sccache
      LITGEN_ROOT: /opt-6/litgen-6085aaa
      CI: 1
      # Keep the supported C++14 cooperative-intrusive configuration in CI.
      CI_CXX14_COOPERATIVE_INTRUSIVE: "yes"
      SCCACHE_BUCKET: my-bucket
      SCCACHE_REGION: us-east-1
      SCCACHE_ENDPOINT: http://172.22.0.14:8333
      SCCACHE_S3_USE_SSL: "false"
      SCCACHE_S3_FORCE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: sccache-user
      AWS_SECRET_ACCESS_KEY: c555a296-edef-459d-f7d2-496d99e93be5
      no_proxy: "localhost,127.0.0.1,172.17.0.1,172.22.0.10,172.22.0.11,172.22.0.12,172.22.0.13,172.22.0.14,woodpecker-server,woodpecker-agent,artifacts-server,seaweed-cache,cont-reg.bjodah.se"
      NO_PROXY: "localhost,127.0.0.1,172.17.0.1,172.22.0.10,172.22.0.11,172.22.0.12,172.22.0.13,172.22.0.14,woodpecker-server,woodpecker-agent,artifacts-server,seaweed-cache,cont-reg.bjodah.se"
    commands:
      - sccache --start-server
      - sccache --show-stats
      - cp -ra $PWD /tmp  # avoids unbuffered(?) disk-write race-condition, /dev/shm has noexec?
      - cd /tmp/`basename $PWD`
      - bash -lc ".ci/run-ci-steps.sh"
      - sccache --show-stats || true
