#!/usr/bin/env python3
"""litgen-driven generator for SymEngine nanobind bindings.

Reads generate.yaml, processes the curated headers through litgen with
the litgen_extensions preprocessing and custom adapters, and writes
generated/symengine_pydef.cpp (binding statements) and generated/symengine.pyi.

Usage (run from repo root):
    python generator/generate.py generator/generate.yaml
    python generator/generate.py generator/generate.yaml --dump-srcml
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import litgen
import yaml
from litgen.internal.adapted_types import AdaptedClass

sys.path.insert(0, str(Path(__file__).parent))
from litgen_extensions import adapt_rcp_basic, preprocess_header
_SUPERPROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_SUPERPROJECT_ROOT))
from tools.binding_codegen.model import load_spec
from tools.binding_codegen.render_nbsymengine import python_excluded_names, render_python_pyi

_BINDING_SPEC = load_spec()


_STUB_HEADER = '''\
# AUTO-GENERATED by generator/generate.py — DO NOT EDIT.
# Requires Python >= 3.13.
import builtins
from typing import overload

# Hand-bound base classes (defined in core_module.cpp)
class Basic: ...
class Number(Basic): ...
class Set(Basic): ...
class Boolean(Basic): ...
'''

# Note: `from __future__ import annotations` is intentionally absent.
# Python >= 3.13 makes it unnecessary (PEP 649 / PEP 749).


# Stubs for functions hand-bound in core_module.cpp that litgen
# cannot generate (they use RCP<const Basic> which is not in the headers
# processed by litgen).
_MANUAL_FUNCTION_STUBS = '''\

# --- Manually-bound function stubs ---

# Factory functions
def symbol(name: str) -> Basic: ...
@overload
def integer(i: int) -> Basic: ...
@overload
def integer(s: str) -> Basic: ...

# Expansion
def expand(expr: Basic) -> Basic: ...

# Logic (hand-bound in core_module.cpp; variadic/container signatures
# that the shared spec's current adapter families cannot express)
def logical_and(*conditions: Boolean) -> Boolean: ...
def logical_or(*conditions: Boolean) -> Boolean: ...
def logical_not(condition: Boolean) -> Boolean: ...
def logical_xor(*conditions: Boolean) -> Boolean: ...
def contains(expr: Basic, set: Set) -> Boolean: ...
def true_const() -> Boolean: ...
def false_const() -> Boolean: ...

# Number theory
def factorial(n: int) -> Basic: ...
def binomial(n: Basic, k: int) -> Basic: ...
def fibonacci(n: int) -> Basic: ...
def lucas(n: int) -> Basic: ...
def mod(n: Basic, d: Basic) -> Basic: ...
def quotient(n: Basic, d: Basic) -> Basic: ...
def mod_f(n: Basic, d: Basic) -> Basic: ...
def quotient_f(n: Basic, d: Basic) -> Basic: ...
def bernoulli(n: int) -> Number: ...
def harmonic(n: int, m: int = 1) -> Number: ...
def gcd_ext(a: Basic, b: Basic) -> tuple: ...
def quotient_mod(a: Basic, b: Basic) -> tuple: ...
def quotient_mod_f(a: Basic, b: Basic) -> tuple: ...
def fibonacci2(n: int) -> tuple: ...
def lucas2(n: int) -> tuple: ...
def crt(rem: list, mod: list) -> Basic | None: ...
def prime_factor_multiplicities(n: Basic) -> dict: ...
def integer_nthroot(a: Basic, n: int) -> tuple: ...
def is_square(n: Basic) -> bool: ...
def perfect_power(n: Basic) -> bool: ...
def cse(exprs: list) -> tuple: ...
# Set factory functions
def finiteset(container: set) -> Basic: ...
def interval(l: Basic, r: Basic, left_open: bool = False, right_open: bool = False) -> Basic: ...
def emptyset() -> Basic: ...
def universalset() -> Basic: ...
def reals() -> Basic: ...
def rationals() -> Basic: ...
def integers() -> Basic: ...
def complexes() -> Basic: ...
def naturals() -> Basic: ...
def naturals0() -> Basic: ...
def set_union(sets: list) -> Set: ...
def set_intersection(sets: list) -> Set: ...
def set_complement(universe: Set, container: Set) -> Set: ...
def conditionset(sym: Basic, condition: Boolean) -> Set: ...
def imageset(sym: Basic, expr: Basic, base: Set) -> Set: ...
def solve(f: Basic, sym: Basic, domain: Set | None = None) -> Set: ...
def linsolve(system: list, syms: list) -> list: ...

# Constants not represented by the shared adapter families
def e() -> Basic: ...
def euler_gamma() -> Basic: ...
def I() -> Basic: ...
def oo() -> Number: ...
def zoo() -> Number: ...
def nan_const() -> Number: ...

# Utility
def str(expr: Basic) -> builtins.str: ...
def same_object(a: Basic, b: Basic) -> bool: ...
def cpp_use_count(a: Basic) -> int: ...
def cast_to_number(x: Basic) -> Number: ...
def real_double(x: float) -> Number: ...
def function_symbol(name: str, *args: Basic) -> Basic: ...
def diff(expr: Basic, sym: Basic) -> Basic: ...
def xreplace(expr: Basic, subs_dict: dict) -> Basic: ...
def subs(expr: Basic, subs_dict: dict) -> Basic: ...
def msubs(expr: Basic, subs_dict: dict) -> Basic: ...
def unevaluated_expr(arg: Basic) -> Basic: ...
def series(expr: Basic, var: Basic, prec: int) -> Number: ...
def _make_derivative(expr: Basic, symbols: list) -> Basic: ...
def _make_subs(expr: Basic, subs_dict: dict) -> Basic: ...
'''


def _get_manual_function_stubs() -> str:
    """Return only declarations for hand-written core_module.cpp bindings."""
    return _MANUAL_FUNCTION_STUBS + "\n"


def _sanitize_stub(stub: str) -> str:
    """Post-process litgen stub to fix invalid Python syntax."""
    # Fix litgen generating invalid Python types for C++ return types
    stub = stub.replace("-> signed int int:", "-> int:")
    stub = stub.replace("-> int int:", "-> int:")
    stub = stub.replace("-> unsigned int int:", "-> int:")
    # Fix C++ type names that are not valid Python
    stub = stub.replace("-> hash_t:", "-> int:")
    stub = stub.replace("-> vec_basic:", "-> list:")
    stub = stub.replace("-> umap_basic_num:", "-> dict:")
    stub = stub.replace("-> map_basic_basic:", "-> dict:")
    stub = stub.replace(": integer_class", ": int")
    stub = stub.replace(": rational_class", ": int")
    stub = stub.replace("-> integer_class:", "-> int:")
    stub = stub.replace("-> rational_class:", "-> int:")
    stub = stub.replace(": map_basic_basic", ": dict")
    stub = stub.replace(": vec_basic", ": list")
    stub = stub.replace(": set_basic", ": set")
    stub = stub.replace("-> set_basic:", "-> set:")
    stub = stub.replace(": set_set", ": set")
    stub = stub.replace("-> set_set:", "-> set:")
    stub = stub.replace(": unsigned", ": int")
    stub = stub.replace("-> unsigned:", "-> int:")
    # Fix invalid escape sequences in docstrings from C++ comments
    # (\p from \param, \c from \class, \return, \file, etc.)
    def _fix_escape_sequences(match: re.Match) -> str:
        s = match.group(0)
        # Double any single backslashes that aren't already doubled
        # and aren't followed by a recognized Python escape char
        return re.sub(r"(?<!\\)\\(?![\\nrtbfav'u\"0-9xU\n])", r"\\\\", s)

    stub = re.sub(r'""".*?"""', _fix_escape_sequences, stub, flags=re.DOTALL)
    return stub


# Intentional comments that must survive stripping.  Anything matching these
# exact strings is kept verbatim (they are injected *after* this filter runs,
# but we list them here so the predicate is self-documenting).
_INTENTIONAL_COMMENTS = frozenset({
    "# Manually-bound classes",
    "# --- Manually-bound function stubs ---",
})


def _strip_echoed_comments(stub: str) -> str:
    """Remove litgen-echoed C++ comments and collapse blank-line runs.

    Applied to the litgen-generated stub *before* manual stub injection, so
    intentional markers added later are unaffected.  We still check against
    ``_INTENTIONAL_COMMENTS`` as a safety net.
    """
    out_lines: list[str] = []
    prev_blank = False
    for line in stub.splitlines():
        stripped = line.strip()

        # Collapse runs of blank lines to a single blank line.
        if not stripped:
            if not prev_blank:
                out_lines.append("")
                prev_blank = True
            continue
        prev_blank = False

        # Never strip intentional markers.
        if stripped in _INTENTIONAL_COMMENTS:
            out_lines.append(line)
            continue

        # Strip echoed C++ location comments: "# some/path.h:42"
        if re.match(r"^#\s*\S+\.\w+:\d+\s*$", stripped):
            continue

        # Strip lines that are entirely a "# /* ... */" echoed C++ signature.
        # (litgen wraps the original C++ signature in /* ... */ when
        # original_signature_flag_show is on; even with it off, stray
        # passthrough can occur.)
        if stripped.startswith("# /*") and stripped.endswith("*/"):
            continue

        # Strip standalone lines that are just a bare C++ "//" comment echoed
        # verbatim, e.g.  "// forward declaration" -> "# // forward declaration"
        if re.match(r"^#\s*//", stripped):
            continue

        out_lines.append(line)

    return "\n".join(out_lines) + "\n"


# SymEngine class hierarchy: maps class name -> base class name.
# litgen generates nb::class_<T, Base> for each; the hand-bound Basic
# provides nb::intrusive_ptr<Basic> which subclasses inherit.
_SYMENTITY_HIERARCHY = {
    # Core
    "Symbol": "Basic",
    "Dummy": "Symbol",
    "Number": "Basic",
    "Integer": "Number",
    "Rational": "Number",
    "Constant": "Basic",
    # Arithmetic
    "Add": "Basic",
    "Mul": "Basic",
    "Pow": "Basic",
    # Functions (leaf classes)
    "Sign": "Basic",
    "Floor": "Basic",
    "Ceiling": "Basic",
    "Truncate": "Basic",
    "Conjugate": "Basic",
    "Sin": "Basic",
    "Cos": "Basic",
    "Tan": "Basic",
    "Cot": "Basic",
    "Csc": "Basic",
    "Sec": "Basic",
    "ASin": "Basic",
    "ACos": "Basic",
    "ATan": "Basic",
    "ACot": "Basic",
    "ASec": "Basic",
    "ACsc": "Basic",
    "ATan2": "Basic",
    "Log": "Basic",
    "LambertW": "Basic",
    "Zeta": "Basic",
    "Dirichlet_eta": "Basic",
    "Sinh": "Basic",
    "Cosh": "Basic",
    "Tanh": "Basic",
    "Coth": "Basic",
    "Sech": "Basic",
    "Csch": "Basic",
    "ASinh": "Basic",
    "ACosh": "Basic",
    "ATanh": "Basic",
    "ACoth": "Basic",
    "ASech": "Basic",
    "ACsch": "Basic",
    "KroneckerDelta": "Basic",
    "Erf": "Basic",
    "Erfc": "Basic",
    "Gamma": "Basic",
    "LowerGamma": "Basic",
    "UpperGamma": "Basic",
    "LogGamma": "Basic",
    "Beta": "Basic",
    "PolyGamma": "Basic",
    "Abs": "Basic",
    "Max": "Basic",
    "Min": "Basic",
    # Boolean / relational
    "Boolean": "Basic",
    "BooleanAtom": "Boolean",
    "And": "Boolean",
    "Or": "Boolean",
    "Not": "Boolean",
    "Xor": "Boolean",
    "Contains": "Boolean",
    "Relational": "Boolean",
    "Equality": "Relational",
    "Unequality": "Relational",
    "LessThan": "Relational",
    "StrictLessThan": "Relational",
    # MultiArgFunction subclasses (Function excluded, so inherit from Basic)
    "LeviCivita": "Basic",
    # Sets
    "Set": "Basic",
    "EmptySet": "Set",
    "UniversalSet": "Set",
    "FiniteSet": "Set",
    "Interval": "Set",
    "Complexes": "Set",
    "Reals": "Set",
    "Rationals": "Set",
    "Integers": "Set",
    "Naturals": "Set",
    "Naturals0": "Set",
    "Union": "Set",
    "Intersection": "Set",
    "Complement": "Set",
    "ConditionSet": "Set",
    "ImageSet": "Set",
}


def _inheritance_callback(cls: AdaptedClass, generated_code_type: litgen.GeneratedCodeType) -> list[str]:
    name = cls.cpp_element().class_name
    if name not in _SYMENTITY_HIERARCHY:
        return []
    base = _SYMENTITY_HIERARCHY[name]
    if generated_code_type == litgen.GeneratedCodeType.stub:
        return [base]
    return [f"SymEngine::{base}"]


def generate(config_yaml_path: str, dump_srcml: bool = False, output_dir: str | None = None) -> None:
    config_path = Path(config_yaml_path)
    if not config_path.is_absolute():
        config_path = Path.cwd() / config_path

    with open(config_path) as f:
        config = yaml.safe_load(f).get("modules", {})

    for module_name, module in config.items():
        options = litgen.LitgenOptions()
        options.use_nanobind()
        options.python_run_black_formatter = False
        options.python_convert_to_snake_case = False
        options.namespaces_root = ["SymEngine"]

        # Determinism: suppress litgen comment/location passthrough into stubs.
        # Prevents "# header.h:42" location markers (non-deterministic paths).
        # (These are already the default, but set explicitly for documentation.)
        options.original_location_flag_show = False
        # Prevents original C++ signature echoed as "# void fn(...) /* original C++ signature */".
        options.original_signature_flag_show = False
        # NOTE: python_reproduce_cpp_layout is left at its default (True) because
        # the .replace() patterns for injecting is_* methods depend on the C++
        # blank-line layout.  Blank-line determinism is handled by
        # _strip_echoed_comments() which collapses blank-line runs.
        # Strip blank lines inside multi-line doc-comments.
        options.python_strip_empty_comment_lines = True

        options.srcmlcpp_options.code_preprocess_function = preprocess_header

        # Keep narrow: no templates, no raw members
        options.class_template_options.add_ignore(r".*")
        options.fn_template_options.add_ignore(r".*")
        options.member_exclude_by_name__regex = r".*"

        # Custom adapter: pass-through for RCP<const Basic> (Phase 6)
        options.fn_custom_adapters = [adapt_rcp_basic]
        options.class_custom_inheritance__callback = _inheritance_callback

        # Per-module excludes from YAML
        class_excludes = module.get("class_exclude", [])
        if class_excludes:
            options.class_exclude_by_name__regex = "|".join(class_excludes)

        fn_excludes = [
            *module.get("fn_exclude", []),
            *python_excluded_names(_BINDING_SPEC),
        ]
        if fn_excludes:
            options.fn_exclude_by_name__regex = "|".join(fn_excludes)

        # Concatenate headers
        source = ""
        for header in module["headers"]:
            header_path = Path(header)
            if not header_path.is_absolute():
                header_path = Path.cwd() / header
            if not header_path.exists():
                print(f"WARNING: header not found: {header_path}")
                continue
            with open(header_path) as fh:
                source += fh.read() + "\n"

        if not source:
            print(f"WARNING: no source for module {module_name}")
            continue

        if dump_srcml:
            import srcmlcpp

            processed = preprocess_header(source)
            xml = srcmlcpp.code_to_srcml_wrapper(
                options.srcmlcpp_options, processed
            )
            print(xml.str_xml(beautify=True))
            return

        generated = litgen.generate_code(options, source)

        # Resolve output paths
        if output_dir is not None:
            out_base = Path(output_dir)
            pydef_path = out_base / Path(module["pydef_path"]).name
            stub_path = out_base / Path(module["stub_path"]).name
        else:
            pydef_path = Path(module["pydef_path"])
            stub_path = Path(module["stub_path"])
            if not pydef_path.is_absolute():
                pydef_path = config_path.parent.parent / pydef_path
            if not stub_path.is_absolute():
                stub_path = config_path.parent.parent / stub_path

        pydef_path.parent.mkdir(parents=True, exist_ok=True)
        stub_path.parent.mkdir(parents=True, exist_ok=True)

        # Write binding code (glue_code + pydef_code)
        with open(pydef_path, "w") as out:
            out.write(generated.glue_code)
            out.write(generated.pydef_code)

        # Write stub (post-process to fix litgen type issues)
        with open(stub_path, "w") as out:
            # Prepend imports and forward-declared base classes
            out.write(_STUB_HEADER)
            stub_text = _sanitize_stub(generated.stub_code)
            # Re-inject is_* member methods that fn_exclude removed
            # (fn_exclude was needed to suppress free tribool is_* from number.h)
            _integer_is_methods = (
                "    def is_zero(self) -> bool:\n"
                "        pass\n"
                "    def is_minus_one(self) -> bool:\n"
                "        pass\n"
                "    def is_positive(self) -> bool:\n"
                "        pass\n"
                "    def is_negative(self) -> bool:\n"
                "        pass\n"
                "    def is_complex(self) -> bool:\n"
                "        pass\n"
            )
            _rational_is_methods = (
                "    def is_zero(self) -> bool:\n"
                "        pass\n"
                "    def is_minus_one(self) -> bool:\n"
                "        pass\n"
                "    def is_positive(self) -> bool:\n"
                "        pass\n"
                "    def is_negative(self) -> bool:\n"
                "        pass\n"
                "    def is_complex(self) -> bool:\n"
                "        pass\n"
            )
            _old_integer = (
                "    def is_one(self) -> bool:\n"
                '        """! \\return `True` if `1`"""\n'
                "        pass\n\n\n\n"
            )
            _new_integer = (
                "    def is_one(self) -> bool:\n"
                '        """! \\return `True` if `1`"""\n'
                "        pass\n"
                + _integer_is_methods + "\n\n\n"
            )
            result = stub_text.replace(_old_integer, _new_integer, 1)
            if result == stub_text:
                raise RuntimeError(
                    "generate.py: failed to inject Integer is_* stubs — "
                    "anchor pattern not found in litgen output.  "
                    "Check if litgen formatting changed."
                )
            stub_text = result

            _old_rational = (
                "    def is_one(self) -> bool:\n"
                '        """! \\return `True` if `1`"""\n'
                "        pass\n"
                "    def is_int(self) -> bool:\n"
                '        """! \\return `True` if denominator is `1`"""\n'
                "        pass\n"
            )
            _new_rational = (
                "    def is_one(self) -> bool:\n"
                '        """! \\return `True` if `1`"""\n'
                "        pass\n"
                "    def is_int(self) -> bool:\n"
                '        """! \\return `True` if denominator is `1`"""\n'
                "        pass\n"
                + _rational_is_methods
            )
            result = stub_text.replace(_old_rational, _new_rational, 1)
            if result == stub_text:
                raise RuntimeError(
                    "generate.py: failed to inject Rational is_* stubs — "
                    "anchor pattern not found in litgen output.  "
                    "Check if litgen formatting changed."
                )
            stub_text = result
            # Strip echoed C++ comments *after* the .replace() calls above,
            # since those patterns rely on exact blank-line counts from litgen.
            stub_text = _strip_echoed_comments(stub_text)
            out.write(stub_text)

            # Append stubs for manually-bound classes that litgen cannot generate
            _MANUAL_STUBS = [
                "class Erf(Basic): ...",
                "class Erfc(Basic): ...",
                "class LogGamma(Basic): ...",
                "class Beta(Basic): ...",
                "class PolyGamma(Basic): ...",
                "class EmptySet(Set): ...",
                "class UniversalSet(Set): ...",
                "class FiniteSet(Set): ...",
                "class ConditionSet(Set): ...",
                "class ImageSet(Set): ...",
                "class BooleanAtom(Boolean): ...",
                "class And(Boolean): ...",
                "class Or(Boolean): ...",
                "class Not(Boolean): ...",
                "class Xor(Boolean): ...",
                "class Contains(Boolean): ...",
                "class Relational(Boolean): ...",
                "class Equality(Relational): ...",
                "class Unequality(Relational): ...",
                "class LessThan(Relational): ...",
                "class StrictLessThan(Relational): ...",
            ]
            out.write("\n# Manually-bound classes\n")
            for line in _MANUAL_STUBS:
                out.write(line + "\n")

            # Append stubs for manually-bound functions
            out.write(_get_manual_function_stubs())
            out.write(render_python_pyi(_BINDING_SPEC))

        print(f"  Generated: {pydef_path}")
        print(f"  Generated: {stub_path}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("config_yaml_path")
    ap.add_argument(
        "--dump-srcml",
        action="store_true",
        help="Dump the srcML XML tree for the preprocessed headers and exit",
    )
    ap.add_argument(
        "--output-dir",
        default=None,
        help="Write generated files to this directory instead of in-place",
    )
    args = ap.parse_args()
    generate(args.config_yaml_path, dump_srcml=args.dump_srcml, output_dir=args.output_dir)


if __name__ == "__main__":
    main()
